export let MOBILES = [
    {
        "id": 1,
        "Name": "OnePlus 7 pro",
        "Brand": "OnePlus",
        "RAM": 8,
        "Primary_Camera": '48 + 12 + 8',
        "Secondary_Camera": 16,
        "ROM": 128,
        "Battery": 3750,
        "Screen": 6.5,
        "Display": "sAMOLED Full HD+",
        "Processor": 845,
        "Warranty": 2,
        "Price": 49999,
        "cover": "../../assets/oneplus7pro1.jpg",
        "images": [
            {"img": "../../assets/oneplus7pro1.jpg"},
            {"img": "../../assets/oneplus7pro2.jpg"},
            {"img": "../../assets/oneplus7pro3.jpg"},
            {"img": "../../assets/oneplus7pro4.jpg"},
            {"img": "../../assets/oneplus7pro5.jpg"},
        ]
    },
    {
        "id": 2,
        "Name": "Redmi Note 7S",
        "Brand": "Redmi",
        "RAM": 3,
        "Primary_Camera": '48 + 8',
        "Secondary_Camera": 8,
        "ROM": 32,
        "Battery": 4000,
        "Screen": 6.1,
        "Display": "IPS LCD",
        "Processor": 660,
        "Warranty": 1,
        "Price": 8999,
        "cover": "../../assets/redmi-note7s.jpg",
        "images": [
            {"img": "../../assets/redmi-note7s.jpg"},
            {"img": "../../assets/redmi-note7s.jpg"},
            {"img": "../../assets/redmi-note7s.jpg"},
            {"img": "../../assets/redmi-note7s.jpg"},
            {"img": "../../assets/redmi-note7s.jpg"},
        ]
    },
    {
        "id": 3,
        "Name": "Realme XT",
        "Brand": "Realme",
        "RAM": 6,
        "Primary_Camera": '48 + 8 + 2 + 2',
        "Secondary_Camera": 32,
        "ROM": 64,
        "Battery": 5000,
        "Screen": 6.36,
        "Display": "sAMOLED Full HD+",
        "Processor": 712,
        "Warranty": 1,
        "Price": 16999,
        "cover": "../../assets/realmext.jpg",
        "images": [
            {"img": "../../assets/realmext.jpg"},
            {"img": "../../assets/realmext.jpg"},
            {"img": "../../assets/realmext.jpg"},
            {"img": "../../assets/realmext.jpg"},
            {"img": "../../assets/realmext.jpg"},
        ]
    },
    {
        "id": 4,
        "Name": "Redmi Note 7 Pro",
        "Brand": "Redmi",
        "RAM": 4,
        "Primary_Camera": '48 + 12',
        "Secondary_Camera": 16,
        "ROM": 64,
        "Battery": 4100,
        "Screen": 6.3,
        "Display": "AMOLED",
        "Processor": 675,
        "Warranty": 2,
        "Price": 12999,
        "cover": "../../assets/redmi-note7pro.jpg",
        "images": [
            {"img": "../../assets/redmi-note7pro.jpg"},
            {"img": "../../assets/redmi-note7pro.jpg"},
            {"img": "../../assets/redmi-note7pro.jpg"},
            {"img": "../../assets/redmi-note7pro.jpg"},
            {"img": "../../assets/redmi-note7pro.jpg"},
        ]
    },
]